global:
  name: consul
  datacenter: dc1
  enterpriseLicense:
    secretName: 'consul-license-secret'
    secretKey: 'license'
  image: "hashicorp/consul-enterprise:1.16.0-ent"


  tls:
    enabled: true

  acls:
    manageSystemACLs: true
    createReplicationToken: true

  gossipEncryption:
    autoGenerate: true

server:
  replicas: 3
  bootstrapExpect: 3
  connect: true

client:
  enabled: true
  replicas: 3
  grpc: true

connectInject:
  enabled: true

controller:
  enabled: true

meshGateway:
  enabled: true
